/**
 * Wave AI — Voice Chat — Transcription Exporter
 */
export class TranscriptionExporter {
  exportTXT(transcript, metadata = {}) {
    const content = `Wave AI Voice Transcription\n${"=".repeat(40)}\nDate: ${new Date().toLocaleString()}\nLanguage: ${metadata.language || "en-US"}\nDuration: ${metadata.duration || "N/A"}s\n\n${transcript}`;
    return this._download(content, "text/plain", `transcription_${Date.now()}.txt`);
  }

  exportSRT(wordTimestamps) {
    const content = wordTimestamps.map((w, i) => {
      const start = this._msToSRT(w.time || i * 2000);
      const end = this._msToSRT((w.time || i * 2000) + 2000);
      return `${i + 1}\n${start} --> ${end}\n${w.text}\n`;
    }).join("\n");
    return this._download(content, "text/plain", `subtitles_${Date.now()}.srt`);
  }

  exportJSON(data) {
    const content = JSON.stringify({ ...data, exportedAt: new Date().toISOString(), app: "Wave AI" }, null, 2);
    return this._download(content, "application/json", `voice_data_${Date.now()}.json`);
  }

  exportMarkdown(transcript, response) {
    const content = `# Wave AI Voice Chat Transcript\n\n*${new Date().toLocaleString()}*\n\n## User\n\n${transcript}\n\n## Wave AI Response\n\n${response}\n\n---\n*Generated by Wave AI — Wave Platforms, Inc.*`;
    return this._download(content, "text/markdown", `voice_chat_${Date.now()}.md`);
  }

  _download(content, mimeType, filename) {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = filename;
    document.body.appendChild(a); a.click(); document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 5000);
    return filename;
  }

  _msToSRT(ms) {
    const h = Math.floor(ms / 3600000), m = Math.floor((ms % 3600000) / 60000), s = Math.floor((ms % 60000) / 1000), cs = ms % 1000;
    return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")},${String(cs).padStart(3, "0")}`;
  }
}
export const transcriptionExporter = new TranscriptionExporter();
