/**
 * Wave AI — ZIP Analysis — Export Report Generator
 */
export class ZipReportExporter {
  generateMarkdown(analysisResult) {
    const { file, structure, projectType, aiSummary, deps, metrics } = analysisResult;
    let md = `# ZIP Analysis Report\n\n*Generated by Wave AI — ${new Date().toLocaleString()}*\n\n---\n\n`;
    md += `## File Information\n- **Filename**: ${file.name}\n- **Size**: ${(file.size / 1024).toFixed(1)} KB\n- **Type**: ${file.type}\n\n`;
    md += `## Project Analysis\n- **Project Type**: ${projectType}\n- **Total Files**: ${structure.totalFiles}\n- **Directories**: ${structure.totalDirs}\n\n`;
    if (aiSummary) md += `## AI Summary\n${aiSummary}\n\n`;
    if (deps?.total > 0) { md += `## Dependencies\n- **Runtime**: ${deps.runtime?.length || 0}\n- **Dev**: ${deps.dev?.length || 0}\n- **Total**: ${deps.total}\n\n`; }
    if (metrics?.totalLines > 0) { md += `## Code Metrics\n- **Files Analyzed**: ${metrics.totalFiles}\n- **Total Lines**: ${metrics.totalLines}\n- **Average Lines/File**: ${metrics.avgLines}\n\n`; }
    md += `---\n*Wave AI — Wave Platforms, Inc.*`;
    return md;
  }
  generateJSON(analysisResult) {
    return JSON.stringify({ ...analysisResult, generatedAt: new Date().toISOString(), generatedBy: "Wave AI", version: "1.0" }, null, 2);
  }
  generateHTML(analysisResult) {
    const md = this.generateMarkdown(analysisResult);
    return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Wave AI ZIP Report</title><style>body{font-family:Arial,sans-serif;max-width:800px;margin:40px auto;padding:20px;} h1{color:#4f7fff;} h2{color:#9b5cff;} code{background:#f4f4f4;padding:2px 4px;border-radius:3px;}</style></head><body><pre>${md}</pre></body></html>`;
  }
  download(content, filename, mimeType = "text/plain") {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href = url; a.download = filename;
    document.body.appendChild(a); a.click(); document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 5000);
  }
  downloadMarkdown(result) { this.download(this.generateMarkdown(result), `zip-report-${Date.now()}.md`); }
  downloadJSON(result) { this.download(this.generateJSON(result), `zip-report-${Date.now()}.json`, "application/json"); }
}
export const zipReportExporter = new ZipReportExporter();
