/**
 * Wave AI Recording Engine — Export Manager
 * Multi-format export: audio/video download, transcript export,
 * share via Web Share API, clipboard copy.
 */

export const EXPORT_FORMATS = {
  audio: [
    { label: "WebM (Original)", ext: "webm", mime: "audio/webm" },
    { label: "WAV (Lossless)", ext: "wav", mime: "audio/wav" },
    { label: "OGG", ext: "ogg", mime: "audio/ogg" },
  ],
  video: [
    { label: "WebM (Original)", ext: "webm", mime: "video/webm" },
    { label: "MP4 (compatible)", ext: "mp4", mime: "video/mp4" },
  ],
  transcript: [
    { label: "Plain text (.txt)", ext: "txt", mime: "text/plain" },
    { label: "SRT subtitles (.srt)", ext: "srt", mime: "text/plain" },
    { label: "JSON data (.json)", ext: "json", mime: "application/json" },
    { label: "Markdown (.md)", ext: "md", mime: "text/markdown" },
  ],
};

export class ExportManager {
  constructor() {
    this.exportHistory = [];
  }

  download(blob, filename, label = "Recording") {
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 10000);
    this.exportHistory.push({ filename, size: blob.size, exportedAt: Date.now(), label });
    return filename;
  }

  downloadAudio(blob, name = "recording") {
    const ext = blob.type.includes("ogg") ? "ogg" : blob.type.includes("mp4") ? "m4a" : "webm";
    const filename = `${name}_${new Date().toISOString().slice(0, 19).replace(/:/g, "-")}.${ext}`;
    return this.download(blob, filename, "Audio");
  }

  downloadVideo(blob, name = "recording") {
    const ext = blob.type.includes("mp4") ? "mp4" : "webm";
    const filename = `${name}_${new Date().toISOString().slice(0, 19).replace(/:/g, "-")}.${ext}`;
    return this.download(blob, filename, "Video");
  }

  downloadTranscript(transcript, format = "txt", metadata = {}) {
    let content, mime, ext;
    switch (format) {
      case "srt":
        content = this._toSRT(transcript);
        mime = "text/plain";
        ext = "srt";
        break;
      case "json":
        content = JSON.stringify({ transcript, metadata, exportedAt: new Date().toISOString() }, null, 2);
        mime = "application/json";
        ext = "json";
        break;
      case "md":
        content = `# Transcript\n\n*Generated by Wave AI*\n\n${transcript}\n\n---\n*${new Date().toLocaleString()}*`;
        mime = "text/markdown";
        ext = "md";
        break;
      default:
        content = transcript;
        mime = "text/plain";
        ext = "txt";
    }
    const blob = new Blob([content], { type: mime });
    const filename = `transcript_${Date.now()}.${ext}`;
    return this.download(blob, filename, "Transcript");
  }

  _toSRT(transcript) {
    const sentences = transcript.split(/[.!?]+/).filter(Boolean);
    return sentences.map((s, i) => {
      const start = this._secToSRT(i * 3);
      const end = this._secToSRT((i + 1) * 3);
      return `${i + 1}\n${start} --> ${end}\n${s.trim()}\n`;
    }).join("\n");
  }

  _secToSRT(sec) {
    const h = Math.floor(sec / 3600);
    const m = Math.floor((sec % 3600) / 60);
    const s = sec % 60;
    return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")},000`;
  }

  async share(blob, title = "Wave AI Recording", text = "Recorded with Wave AI") {
    if (!navigator.share) return { success: false, error: "Web Share API not supported" };
    try {
      const ext = blob.type.includes("video") ? "webm" : "webm";
      const file = new File([blob], `wave_recording.${ext}`, { type: blob.type });
      await navigator.share({ title, text, files: [file] });
      return { success: true };
    } catch (err) {
      if (err.name === "AbortError") return { success: false, error: "Share cancelled" };
      return { success: false, error: err.message };
    }
  }

  async copyToClipboard(text) {
    try {
      await navigator.clipboard.writeText(text);
      return { success: true };
    } catch {
      const el = document.createElement("textarea");
      el.value = text;
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
      return { success: true };
    }
  }

  createObjectURL(blob) { return URL.createObjectURL(blob); }
  revokeObjectURL(url) { URL.revokeObjectURL(url); }

  getExportHistory() { return [...this.exportHistory]; }
  clearHistory() { this.exportHistory = []; }
}

export const exportManager = new ExportManager();
