/* ═══════════════════════════════════════════════════════════════
   Wave AI — HuggingFace Provider
   Primary model backbone using open-source models via HuggingFace
   Inference API. Supports Mistral, Llama, Falcon, BLOOM, and more.
═══════════════════════════════════════════════════════════════ */

import WAVE_CONFIG from "@/lib/config";
import { formatMistralPrompt, ChatMessage, approximateTokenCount } from "@/lib/tokenizer";

export interface HFGenerationOptions {
  temperature?: number;
  topP?: number;
  topK?: number;
  maxNewTokens?: number;
  repetitionPenalty?: number;
  doSample?: boolean;
  stopSequences?: string[];
  stream?: boolean;
}

export interface HFResponse {
  text: string;
  model: string;
  tokens: number;
  finishReason: "stop" | "length" | "error";
  latencyMs: number;
  cached: boolean;
}

export interface HFModelInfo {
  id: string;
  name: string;
  type: "chat" | "completion" | "code" | "embedding";
  contextLength: number;
  isAvailable: boolean;
}

const BASE_URL = WAVE_CONFIG.huggingface.baseUrl;
const MODELS = WAVE_CONFIG.huggingface.models;

/* ── Response cache ──────────────────────────────────────────── */
const hfCache = new Map<string, { text: string; ts: number }>();
const CACHE_TTL = 1000 * 60 * 30;
const CACHE_MAX = 200;

function getCacheKey(model: string, prompt: string): string {
  return `${model}::${prompt.slice(0, 400)}`;
}

/* ── Core fetch ──────────────────────────────────────────────── */
async function hfFetch(
  model: string,
  payload: Record<string, unknown>,
  apiKey?: string,
  signal?: AbortSignal
): Promise<unknown> {
  const url = `${BASE_URL}/${model}`;
  const headers: Record<string, string> = { "Content-Type": "application/json" };
  if (apiKey) headers["Authorization"] = `Bearer ${apiKey}`;

  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), WAVE_CONFIG.huggingface.timeout);
  if (signal) signal.addEventListener("abort", () => ctrl.abort(), { once: true });

  try {
    const res = await fetch(url, {
      method: "POST",
      headers,
      body: JSON.stringify(payload),
      signal: ctrl.signal,
    });
    clearTimeout(timer);

    if (res.status === 503) {
      const err = await res.json().catch(() => ({}));
      if ((err as { estimated_time?: number }).estimated_time) {
        throw new Error(`Model loading, retry in ${Math.ceil((err as { estimated_time: number }).estimated_time)}s`);
      }
    }

    if (!res.ok) throw new Error(`HuggingFace API error: ${res.status}`);
    return await res.json();
  } catch (e) {
    clearTimeout(timer);
    throw e;
  }
}

/* ── Text generation ─────────────────────────────────────────── */
export async function generateText(
  prompt: string,
  options: HFGenerationOptions = {},
  apiKey?: string,
  signal?: AbortSignal
): Promise<HFResponse> {
  const model = MODELS.chat;
  const start = performance.now();

  const ck = getCacheKey(model, prompt);
  const cached = hfCache.get(ck);
  if (cached && Date.now() - cached.ts < CACHE_TTL) {
    return {
      text: cached.text,
      model,
      tokens: approximateTokenCount(cached.text),
      finishReason: "stop",
      latencyMs: 0,
      cached: true,
    };
  }

  const payload = {
    inputs: prompt,
    parameters: {
      max_new_tokens: options.maxNewTokens ?? WAVE_CONFIG.model.maxTokens,
      temperature: options.temperature ?? WAVE_CONFIG.model.temperature,
      top_p: options.topP ?? WAVE_CONFIG.model.topP,
      top_k: options.topK ?? WAVE_CONFIG.model.topK,
      repetition_penalty: options.repetitionPenalty ?? WAVE_CONFIG.model.repetitionPenalty,
      do_sample: options.doSample ?? true,
      return_full_text: false,
      stop: options.stopSequences ?? ["</s>", "[INST]", "User:", "Human:"],
    },
    options: { wait_for_model: true, use_cache: true },
  };

  const data = await hfFetch(model, payload, apiKey, signal) as Array<{ generated_text: string }> | { generated_text: string };
  const generated = Array.isArray(data) ? data[0]?.generated_text : (data as { generated_text?: string }).generated_text;

  if (!generated) throw new Error("No text generated by HuggingFace model");

  const text = generated.trim();
  if (hfCache.size >= CACHE_MAX) {
    const first = hfCache.keys().next().value;
    if (first) hfCache.delete(first);
  }
  hfCache.set(ck, { text, ts: Date.now() });

  return {
    text,
    model,
    tokens: approximateTokenCount(text),
    finishReason: "stop",
    latencyMs: Math.round(performance.now() - start),
    cached: false,
  };
}

/* ── Chat completion ─────────────────────────────────────────── */
export async function chatCompletion(
  messages: ChatMessage[],
  options: HFGenerationOptions = {},
  apiKey?: string,
  signal?: AbortSignal
): Promise<HFResponse> {
  const prompt = formatMistralPrompt(messages);
  return generateText(prompt, options, apiKey, signal);
}

/* ── Code generation ─────────────────────────────────────────── */
export async function generateCode(
  prompt: string,
  language?: string,
  apiKey?: string,
  signal?: AbortSignal
): Promise<HFResponse> {
  const codePrompt = `You are an expert software engineer. Write clean, production-quality${language ? ` ${language}` : ""} code.\n\n${prompt}\n\nCode:`;
  return generateText(codePrompt, {
    temperature: 0.2,
    maxNewTokens: 2048,
    stopSequences: ["</s>", "Human:", "User:"],
  }, apiKey, signal);
}

/* ── Summarization ───────────────────────────────────────────── */
export async function summarize(
  text: string,
  maxLength = 150,
  apiKey?: string
): Promise<string> {
  const model = MODELS.summarization;
  const payload = {
    inputs: text.slice(0, 4096),
    parameters: { max_length: maxLength, min_length: 30, do_sample: false },
    options: { wait_for_model: true },
  };

  try {
    const data = await hfFetch(model, payload, apiKey) as Array<{ summary_text: string }>;
    return Array.isArray(data) ? data[0]?.summary_text ?? "" : "";
  } catch {
    const sentences = text.split(/[.!?]+/).filter(Boolean);
    return sentences.slice(0, 3).join(". ").trim();
  }
}

/* ── Zero-shot classification ────────────────────────────────── */
export async function classify(
  text: string,
  labels: string[],
  apiKey?: string
): Promise<{ label: string; score: number }[]> {
  const model = MODELS.classification;
  const payload = {
    inputs: text,
    parameters: { candidate_labels: labels },
    options: { wait_for_model: true },
  };

  try {
    const data = await hfFetch(model, payload, apiKey) as { labels: string[]; scores: number[] };
    if (!data.labels) return labels.map(l => ({ label: l, score: 1 / labels.length }));
    return data.labels.map((label, i) => ({ label, score: data.scores[i] }));
  } catch {
    return labels.map(l => ({ label: l, score: 1 / labels.length }));
  }
}

/* ── Sentiment analysis ──────────────────────────────────────── */
export async function analyzeSentiment(
  text: string,
  apiKey?: string
): Promise<{ label: "POSITIVE" | "NEGATIVE" | "NEUTRAL"; score: number }> {
  const model = MODELS.sentiment;
  const payload = {
    inputs: text.slice(0, 512),
    options: { wait_for_model: true },
  };

  try {
    const data = await hfFetch(model, payload, apiKey) as Array<Array<{ label: string; score: number }>>;
    const results = Array.isArray(data) ? data[0] : [];
    const best = results.sort((a: { score: number }, b: { score: number }) => b.score - a.score)[0];
    return { label: (best?.label ?? "NEUTRAL") as "POSITIVE" | "NEGATIVE" | "NEUTRAL", score: best?.score ?? 0.5 };
  } catch {
    return { label: "NEUTRAL", score: 0.5 };
  }
}

/* ── Named entity recognition ────────────────────────────────── */
export async function extractEntities(
  text: string,
  apiKey?: string
): Promise<Array<{ entity: string; word: string; score: number }>> {
  const model = MODELS.ner;
  const payload = {
    inputs: text.slice(0, 512),
    options: { wait_for_model: true },
  };

  try {
    const data = await hfFetch(model, payload, apiKey) as Array<{ entity_group?: string; entity?: string; word: string; score: number }>;
    return Array.isArray(data) ? data.map(e => ({
      entity: e.entity_group ?? e.entity ?? "UNKNOWN",
      word: e.word,
      score: e.score,
    })) : [];
  } catch {
    return [];
  }
}

/* ── Model availability check ────────────────────────────────── */
export async function checkModelAvailability(model: string, apiKey?: string): Promise<boolean> {
  try {
    await fetch(`https://api-inference.huggingface.co/models/${model}`, {
      method: "HEAD",
      headers: apiKey ? { Authorization: `Bearer ${apiKey}` } : {},
    });
    return true;
  } catch {
    return false;
  }
}

/* ── Available models list ───────────────────────────────────── */
export const AVAILABLE_MODELS: HFModelInfo[] = [
  { id: MODELS.chat, name: "Mistral 7B Instruct", type: "chat", contextLength: 8192, isAvailable: true },
  { id: MODELS.code, name: "Codestral 22B", type: "code", contextLength: 32768, isAvailable: true },
  { id: MODELS.embedding, name: "MiniLM L6 v2", type: "embedding", contextLength: 512, isAvailable: true },
  { id: MODELS.summarization, name: "BART Large CNN", type: "completion", contextLength: 4096, isAvailable: true },
  { id: "tiiuae/falcon-7b-instruct", name: "Falcon 7B Instruct", type: "chat", contextLength: 4096, isAvailable: true },
  { id: "bigscience/bloom-7b1", name: "BLOOM 7B", type: "completion", contextLength: 2048, isAvailable: true },
  { id: "HuggingFaceH4/zephyr-7b-beta", name: "Zephyr 7B Beta", type: "chat", contextLength: 4096, isAvailable: true },
  { id: "teknium/OpenHermes-2.5-Mistral-7B", name: "OpenHermes 2.5 Mistral", type: "chat", contextLength: 8192, isAvailable: true },
];

export function clearHFCache(): void { hfCache.clear(); }
export function hfCacheSize(): number { return hfCache.size; }
